#!/usr/bin/perl

# vim: syntax=perl:

##  Useful webpages :-
##  http://www.imagemagick.org/script/command-line-processing.php
##  http://www.imagemagick.org/script/perl-magick.php

use strict ;
use warnings ;
use v5.40.1 ;

use lib `fvwm-perllib dir`;
use FVWM::Module;
use Data::Dump qw( dump ) ;
use Image::Magick ;             ##  libimage-magick-perl
use Path::Tiny ;
use File::stat ;
use Try::Tiny ;
use IPC::Run qw( run timeout ) ;

##  Maximum thumbnail dimensions.
my $width = 320 ;
my $height = 240 ;
##  Number of times to attempt window capture
my $tries = 3 ;
##  Expiration time in seconds for saved thumbnails.
my $expires = 100 ;
##  Destination folder for thumbnails.
my $folder = "/home/deer/.fvwm/images/thumbs" ;

##  Enable/disable logging
my $logfile = path("/tmp/Thumbnail.log") ;
unlink $logfile ;
my $logger = "yes" ;
#my $logger = "" ;

my $module = FVWM::Module->new(
    Name => 'Thumbnail',
    Debug => 0,
);

my $modname = $module->name ;

##  Fvwm module reads config before listening for SendToModule cmnds.
##
$module->add_handler(M_CONFIG_INFO, \&read_config) ;
$module->add_handler(M_END_CONFIG_INFO, sub {
        $module->show_message("[$modname] read config finished]") ;
    $module->addHandler(M_STRING, \&process_cmd);
    });

#$module->show_message("Starting");
$module->send("Send_ConfigInfo");
$module->event_loop ;

####  SUBROUTINES

##  Two functions to read and process entries from the module config
##  during startup.
##
sub read_config {
    my ($module, $event) = @_ ;
    return unless $event->_text =~ /^\*$modname(.*)$/ ;
    process_config($1);
}

sub process_config {
    my ($s) = @_ ;
    my ($option, $args) = $s =~ /\s*(\w+)\s*(.*)/;

    my %opts = (
        Width => sub { $width = $args },
        Height => sub { $height = $args },
        Tries => sub { $tries = $args },
        Expire => sub { $expires = $args },
    ) ;

    if (defined $opts{$option}) {
        $opts{$option}() ;
    } else {
        $module->showMessage("Unknown option \"$option\"");
    }
}

##  To process and run commands received via SendToModule cmnds.
##
sub process_cmd {

    my ($module, $event) = @_ ;
    my ($s) = $event->_text ;
    my ($command, $arg) = $s =~ /\s*(\w+)\s*(.*)/ ;

    my %cmd = (
        capture  => sub { thumbnail($arg) },
    ) ;

    if (defined $cmd{$command}) {

        logger("===========================") ;
        logger("$modname: process_cmd() : $command $arg") ;
        $cmd{$command}() ;
        $module->showMessage("debug: $command");
        logger("$modname: process_cmd() : $command $arg") ;
    } else {
        logger("$modname: process_cmd() : unknown : $command $arg") ;
        $module->showMessage("unknown command \"$command $arg\"");
    }
}

##  To thumbnail the current window, if existing image has not expired.
##
sub thumbnail  {

    my $widhex = shift ;
    ##  Destination filename for the thumbnail. 
    my $pngfile = "$folder/$widhex.png" ;

    if ( !-e $pngfile or expired($pngfile)) {

        logger("$modname: thumbnail() :  new thumb required") ;

        ##  capture image of current window
        my $thumb = capture($widhex) ;
        logger("$modname: capture() failed ") if not $thumb ;
        return 0 if not $thumb ;
        logger("$modname: capture() succeeded ") ;

        ##  Fit the full frame within the bounds, without enlarging small windows.
        return 0 if $thumb->Thumbnail(geometry => "${width}x$height>") ;
        logger("$modname: im->thumbnail() succeeded ") ;

        ##  Save the finished thumbnail.
        unless ($thumb && ref $thumb) {
            logger("$modname: thumbnail() : thumb object invalid");
            return 0;
        }
        logger("$modname: thumbnail() : about to write $pngfile");
        my $err = $thumb->Write(filename => $pngfile, quality => 100);
        if ($err) {
            logger("$modname: im->Write() failed for $pngfile: $err");
            return 0;
        }
        logger("$modname: im->Write() succeeded for $pngfile");
    } else {
        logger("$modname: current thumb valid") ;
    }

    return 1 ;
}

##  Cheap liveness probe for a window id.
##
##  xwininfo exits nonzero for an id the server does not know about and, unlike
##  import, never grabs the pointer when it fails -- which makes it safe to ask
##  speculatively.  Measured at under a millisecond.
##
sub window_alive {
    my $wid = shift ;
    my $ok = eval {
        run( [ 'xwininfo', '-id', $wid ], \undef, \my $out, \my $err, timeout(5) ) ;
    } ;
    return $ok ? 1 : 0 ;
}

##  To capture an image of the current window.
sub capture  {
    my $widhex = shift ;
    my $wid = hex($widhex) ;
    my $tmp_png = "$folder/$widhex.tmp.png" ;

    logger("$modname: begin capture() ");
    unlink $tmp_png;

    ##  Captures arrive via "Schedule 100 ... SendToModule Thumbnail capture
    ##  $[w.id]", so the window can easily be gone by the time we run: any
    ##  short-lived focused window (the alt-tab picker, a dismissed dialog)
    ##  routinely is.  Handed an id it cannot find, "import" does NOT just
    ##  fail -- it falls back to INTERACTIVE selection, grabbing the pointer
    ##  and blocking on a click.  That freezes input and stalls every X client
    ##  behind it until the user clicks somewhere.  So never hand import an id
    ##  we have not just confirmed is alive.
    unless (window_alive($wid)) {
        logger("$modname: capture() : window $widhex is gone, skipping") ;
        return 0 ;
    }

    ##  -silent suppresses the capture beep.  The timeout is a hard backstop
    ##  for the race between the liveness check above and import connecting:
    ##  bounded disruption beats an indefinite pointer grab.
    my @cmd = ( 'import', '-silent', '-window', $wid, $tmp_png ) ;
    logger("$modname: running: @cmd");
    my $rc = eval {
        run( \@cmd, \undef, \my $out, \my $err, timeout(5) ) ;
    } ;
    logger("$modname: capture() : import aborted: $@") if $@ ;

    unless ($rc && -e $tmp_png) {
        logger("$modname: capture() : import failed for $tmp_png");
        unlink $tmp_png ;
        return 0;
    }

    my $thumb = Image::Magick->New();
    my $err = $thumb->Read($tmp_png);
    unlink $tmp_png;

    if ($err) {
        logger("$modname: im->Read() fails for $tmp_png: $err");
        return 0;
    }
    logger("$modname: capture() succeeded, read $tmp_png");
    return $thumb;
}

##  Return 1 if $file was modified more that $expired seconds ago.
##
sub expired {
    my $file = shift ;
    my $diff = time() - stat($file)->mtime ;
    if ($diff > $expires) { return 1 } else { return 0 } ;
}

sub logger {
    return 0 unless $logger ;
    my $msg = shift ;
    $msg .= "\n" ;
    $logfile->append_utf8($msg) ; 
}

